name: wifi_sync CI

on:
  push:
    paths:
      - "examples/wifi_sync/**"
      - ".github/workflows/wifi_sync.yml"
  pull_request:
    paths:
      - "examples/wifi_sync/**"
      - ".github/workflows/wifi_sync.yml"

jobs:
  wifi_sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: |
        cd examples/wifi_sync
        pio run
